name: Deploy

on:
  push:

jobs:
  deploy:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      - name: Install Scoop & GCC
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          scoop install gcc
        shell: pwsh

      - name: Build
        run: |
          C:\Users\runneradmin\scoop\apps\gcc\current\bin\g++.exe -g main.cpp -o FuckWindows.exe
        shell: pwsh